<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../Zombies.Engine.Core/Zombies.Engine.Core.csproj" />
    <ProjectReference Include="../Zombies.Engine.Ecs/Zombies.Engine.Ecs.csproj" />
    <ProjectReference Include="../Zombies.Engine.Net/Zombies.Engine.Net.csproj" />
    <ProjectReference Include="../Zombies.Engine.Voxel/Zombies.Engine.Voxel.csproj" />
    <ProjectReference Include="../Zombies.Domain.Zombies/Zombies.Domain.Zombies.csproj" />
  </ItemGroup>

</Project>
