<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Zombies.Engine.Core/Zombies.Engine.Core.csproj" />
    <ProjectReference Include="../../src/Zombies.Engine.Voxel/Zombies.Engine.Voxel.csproj" />
    <ProjectReference Include="../../src/Zombies.Engine.Render/Zombies.Engine.Render.csproj" />
    <ProjectReference Include="../../src/Zombies.Engine.Net/Zombies.Engine.Net.csproj" />
    <ProjectReference Include="../../src/Zombies.Domain.World/Zombies.Domain.World.csproj" />
  </ItemGroup>

</Project>
