<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Zombies.Engine.Core/Zombies.Engine.Core.csproj" />
    <ProjectReference Include="../Zombies.Engine.Render/Zombies.Engine.Render.csproj" />
    <ProjectReference Include="../Zombies.Engine.Render.Vulkan/Zombies.Engine.Render.Vulkan.csproj" />
    <ProjectReference Include="../Zombies.Engine.Platform/Zombies.Engine.Platform.csproj" />
    <ProjectReference Include="../Zombies.Engine.Ui/Zombies.Engine.Ui.csproj" />
    <ProjectReference Include="../Zombies.Engine.Net/Zombies.Engine.Net.csproj" />
    <ProjectReference Include="../Zombies.Engine.Physics/Zombies.Engine.Physics.csproj" />
  </ItemGroup>

</Project>
