<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageVersion Include="UnitsNet" Version="5.75.1" />
    <PackageVersion Include="ppy.SDL3-CS" Version="2026.1002.1" />
    <PackageVersion Include="Silk.NET.Vulkan" Version="2.23.0" />
    <PackageVersion Include="Silk.NET.Vulkan.Extensions.KHR" Version="2.23.0" />
    <PackageVersion Include="Silk.NET.Vulkan.Extensions.NV" Version="2.23.0" />
    <PackageVersion Include="Silk.NET.Vulkan.Extensions.EXT" Version="2.23.0" />
    <PackageVersion Include="LiteNetLib" Version="2.1.4" />
    <PackageVersion Include="JoltPhysicsSharp" Version="2.22.0" />
    <PackageVersion Include="Microsoft.Direct3D.DXC" Version="1.10.2605.37-preview" />
  </ItemGroup>

</Project>
