<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="LiteNetLib" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Zombies.Engine.Core/Zombies.Engine.Core.csproj" />
    <ProjectReference Include="../Zombies.Engine.Animation/Zombies.Engine.Animation.csproj" />
    <ProjectReference Include="../Zombies.Engine.Ecs/Zombies.Engine.Ecs.csproj" />
    <ProjectReference Include="../Zombies.Domain.Combat/Zombies.Domain.Combat.csproj" />
    <ProjectReference Include="../Zombies.Domain.Death/Zombies.Domain.Death.csproj" />
    <ProjectReference Include="../Zombies.Domain.Inventory/Zombies.Domain.Inventory.csproj" />
    <ProjectReference Include="../Zombies.Domain.StatusEffects/Zombies.Domain.StatusEffects.csproj" />
    <ProjectReference Include="../Zombies.Domain.Survival/Zombies.Domain.Survival.csproj" />
    <ProjectReference Include="../Zombies.Domain.World/Zombies.Domain.World.csproj" />
    <ProjectReference Include="../Zombies.Domain.Zombies/Zombies.Domain.Zombies.csproj" />
  </ItemGroup>

</Project>
