<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Zombies.Engine.Core/Zombies.Engine.Core.csproj" />
    <ProjectReference Include="../../src/Zombies.Domain.Inventory/Zombies.Domain.Inventory.csproj" />
    <ProjectReference Include="../../src/Zombies.Engine.Render/Zombies.Engine.Render.csproj" />
    <ProjectReference Include="../../src/Zombies.Engine.Platform/Zombies.Engine.Platform.csproj" />
    <ProjectReference Include="../../src/Zombies.Engine.Voxel/Zombies.Engine.Voxel.csproj" />
  </ItemGroup>

</Project>
