<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Zombies.Domain.Items/Zombies.Domain.Items.csproj" />
    <ProjectReference Include="../../src/Zombies.Domain.Inventory/Zombies.Domain.Inventory.csproj" />
    <ProjectReference Include="../../src/Zombies.Domain.Combat/Zombies.Domain.Combat.csproj" />
    <ProjectReference Include="../../src/Zombies.Domain.Survival/Zombies.Domain.Survival.csproj" />
    <ProjectReference Include="../../src/Zombies.Domain.Mods/Zombies.Domain.Mods.csproj" />
    <ProjectReference Include="../../src/Zombies.Domain.Crafting/Zombies.Domain.Crafting.csproj" />
  </ItemGroup>

</Project>
