<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Zombies.Persistence.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Zombies.Domain.Items/Zombies.Domain.Items.csproj" />
    <ProjectReference Include="../Zombies.Domain.Inventory/Zombies.Domain.Inventory.csproj" />
    <ProjectReference Include="../Zombies.Domain.Mods/Zombies.Domain.Mods.csproj" />
    <ProjectReference Include="../Zombies.Domain.Combat/Zombies.Domain.Combat.csproj" />
    <ProjectReference Include="../Zombies.Domain.Survival/Zombies.Domain.Survival.csproj" />
    <ProjectReference Include="../Zombies.Domain.Death/Zombies.Domain.Death.csproj" />
    <ProjectReference Include="../Zombies.Engine.Voxel/Zombies.Engine.Voxel.csproj" />
  </ItemGroup>

</Project>

