<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Zombies.Engine.Core/Zombies.Engine.Core.csproj" />
    <ProjectReference Include="../Zombies.Engine.Ecs/Zombies.Engine.Ecs.csproj" />
    <ProjectReference Include="../Zombies.Engine.Net/Zombies.Engine.Net.csproj" />
  </ItemGroup>

</Project>
